name: release
description: release
inputs:
  registry:
    type: string
    description: GAR registry to use when publishing
    default: "europe-docker.pkg.dev"
  repo:
    type: string
    description: GAR repo to use when publishing
    default: "da-images/public-unstable"
  flags:
    type: string
    description: Additional flags to pass to goreleaser
    default: "--snapshot"
  key:
    type: string
    description: auth key
    required: true
  gh_token:
    description: github auth secret
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      with:
        fetch-depth: 0
    - uses: ./.github/actions/nix
    - uses: ./.github/actions/gcloud-login
      with:
        key: ${{ inputs.key }}
    - run: |
        export GIT_COMMIT_COUNT=$(git rev-list --count HEAD)
        goreleaser ${{ inputs.flags }}
      shell: bash -euo pipefail -c "source nix.source && exec bash {0}"
    - uses: ./.github/actions/nsis
      with:
        bin-path: dist/windows/amd64/dpm.exe
        out: dist/dpm-installer.exe
    - name: Create draft GitHub Release
      env:
        GITHUB_TOKEN: ${{ inputs.gh_token }}
        RELEASE_NAME: 0.0.0-skiprelease
      run: |
        git tag "${RELEASE_NAME}"
        git push --tag origin 0.0.0-skiprelease
        gh release create "${RELEASE_NAME}" \
          dist/linux/arm64/dpm \
          dist/linux/amd64/dpm \
          dist/darwin/arm64/dpm \
          dist/darwin/amd64/dpm \
          dist/windows/amd64/dpm.exe \
          dist/dpm-installer.exe \
          --draft \
          --generate-notes \
          --title "${RELEASE_NAME}"
      shell: bash -euo pipefail -c "source nix.source && exec bash {0}"
