name: release
description: release
inputs:
  registry:
    type: string
    description: GAR registry to use when publishing
    default: "europe-docker.pkg.dev"
  repo:
    type: string
    description: GAR repo to use when publishing
    default: "da-images/public-unstable"
  flags:
    type: string
    description: Additional flags to pass to goreleaser
    default: "--snapshot"
  key:
    type: string
    description: auth key
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      with:
        fetch-depth: 0
    - uses: ./.github/actions/nix
    - uses: ./.github/actions/gcloud-login
      with:
        key: ${{ inputs.key }}
    - run: |
        export GIT_COMMIT_COUNT=$(git rev-list --count HEAD)
        goreleaser ${{ inputs.flags }}
      shell: bash -euo pipefail -c "source nix.source && exec bash {0}"
    - name: dpm publish dry-run
      run: make publish-release-to-gar ASSISTANT_ARGS='-d'
      shell: bash -euo pipefail -c "source nix.source && exec bash {0}"
    - name: dpm publish to ${{ inputs.repo }}
      run: make publish-release-to-gar ASSISTANT_ARGS='--registry ${{ inputs.registry }}/${{ inputs.repo }} -t latest'
      shell: bash -euo pipefail -c "source nix.source && exec bash {0}"
    - uses: ./.github/actions/nsis
      with:
        bin-path: dist/windows/amd64/dpm.exe
        out: dist/dpm-installer.exe
    - name: publish windows installer to bucket
      run: ./.github/actions/release/publish-windows.sh
      shell: bash -euo pipefail -c "source nix.source && exec bash {0}"
