name: release
description: release
inputs:
  registry:
    type: string
    description: GAR registry to use when publishing
    default: "europe-docker.pkg.dev"
  repo:
    type: string
    description: GAR repo to use when publishing
    default: "da-images/public-unstable"
  flags:
    type: string
    description: Additional flags to pass to goreleaser
    default: "--snapshot"
  key:
    type: string
    description: auth key
    required: true
  gh_token:
    description: github auth secret
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      with:
        fetch-depth: 0
    - uses: ./.github/actions/nix
    - uses: ./.github/actions/gcloud-login
      with:
        key: ${{ inputs.key }}
    - run: |
        export GIT_COMMIT_COUNT=$(git rev-list --count HEAD)
        goreleaser ${{ inputs.flags }}
        DPM_BIN_VERSION="$(cat dist/metadata.json | jq -r .version)"
        echo "DPM_BIN_VERSION=${DPM_BIN_VERSION}" >> "${GITHUB_ENV}"
      shell: bash -euo pipefail -c "source nix.source && exec bash {0}"
    - uses: ./.github/actions/nsis
      with:
        bin-path: dist/windows/amd64/dpm.exe
        out: dist/dpm-installer-${DPM_BIN_VERSION}-windows-amd64.exe
    - name: Create draft GitHub Release
      env:
        GH_TOKEN: ${{ inputs.gh_token }}
        RELEASE_TAG: 0.0.0-skiprelease
      run: |
        git tag -f "${RELEASE_TAG}"
        git push -f --tag origin "${RELEASE_TAG}"
        gh release create "${RELEASE_TAG}" \
          dist/dpm-* \
          --draft \
          --generate-notes \
          --title "${RELEASE_TAG}"
      shell: bash -euo pipefail -c "source nix.source && exec bash {0}"
