name: Static checks

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  workflow-policy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Lint Actions Yaml
        uses: raven-actions/actionlint@3d39aea434753780c3b3d4a1a31c854b4dbf49d7 # v2

      - name: Check for workflow changes
        if: ${{ github.event.pull_request.head.repo.fork == true }}
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
          PR: ${{ github.event.pull_request.number }}
        run: |
          files="$(gh api \
            --paginate \
            "repos/$REPO/pulls/$PR/files" \
            --jq '.[].filename')"

          if echo "$files" | grep -q '^\.github/'; then
            echo "::error title=Workflow Changes::Pull requests from forks should not modify GitHub Actions workflows."
            exit 1
          fi
          
          pattern='^(.*/?(go\.mod|go\.sum|requirements.*\.txt|pyproject\.toml|poetry\.lock|Pipfile|Pipfile\.lock|uv\.lock|build\.sbt|pom\.xml|flake\.lock|package-lock\.json|yarn\.lock|pnpm-lock\.yaml|Cargo\.lock|Gemfile\.lock))$'
          if echo "$files" | grep -qE "$pattern"; then
              echo "::warning title=Dependency changes::Pull requests from forks should not modify dependency/lock files."
              exit 1
          fi
