name: Check workflow changes

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  workflow-policy:
    runs-on: ubuntu-latest

    if: github.event.pull_request.head.repo.fork == true
    steps:
      - name: Check for workflow changes
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
          PR: ${{ github.event.pull_request.number }}
        run: |
          files="$(gh api \
            --paginate \
            "repos/$REPO/pulls/$PR/files" \
            --jq '.[].filename')"

          if echo "$files" | grep -q '^\.github/'; then
            echo "::error::This PR modifies GitHub Actions workflows."
            exit 1
          fi
          
          pattern='^(.*/?(go\.mod|go\.sum|requirements.*\.txt|pyproject\.toml|poetry\.lock|Pipfile|Pipfile\.lock|uv\.lock|build\.sbt|pom\.xml|flake\.lock|package-lock\.json|yarn\.lock|pnpm-lock\.yaml|Cargo\.lock|Gemfile\.lock))$'
          if echo "$files" | grep -qE "$pattern"; then
              echo "::error::Pull requests from forks are not allowed to modify dependency/lock files."
              exit 1
          1